language: python
python:
  - "3.5"
  - "3.6"
sudo: false

before_install: pip install codecov
after_success:  codecov

install:
  - pip install numpy
  - pip install -r requirements.txt
  - python install_resources.py omssa_2_1_9

script: nosetests --with-coverage
